### ISSUE TITLE
Autocompletion for Prophecy 

### ISSUE THREAD

**Issue by dbalabka** [maxfilatov/phpuaca#5] opened 2015-07-20 18:29 UTC
Starting from PHPUnit version 4.5 it [supports Prophecy out-of-the-box](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.5.md#added). The major problem to use it is (same as for standart PHPUnit mocking functionality) PHPStorm do not know how to autocomplite, because of magic methods.
It will be very usefull to implement this feature.
![image](https://cloud.githubusercontent.com/assets/1269372/8783727/5593d76c-2f26-11e5-8fd8-33be4fb5c8e7.png)

**Comment by King2500** [comment] 2016-01-02 01:13
I already added a TypeProvider with Prophecy support. I'll create a Pull request after the other requests were merged.

**Comment by maxfilatov** [comment] 2016-01-04 10:14
In my opinion it’s quite enough to use type hinting to solve these cases:

``` php
/** @var \Doctrine\ORM\EntityRepository | \Prophecy\ObjectProphecy $repo */
 $repo = $this->prophesize('\Doctrine\ORM\EntityRepository');
 $repo->findOneBy(...);
```

``` php
/** @var \DateTime | \PHPUnit_Framework_MockObject_MockObject $Mock */
 $Mock = $this->getMockBuilder(\DateTime::class)
     ->disableOriginalConstructor() 
    ->setMethods(
        array( 
            'format', 
        ) 
    ) 
    ->getMock();

$Mock->modify('+1 day');
```

Type provider will be applicable just for developers with installed plugin, type hinting - for all developers in the team.

And some useful live templates for MockBuilder/MockObject to make some things like type hinting easier:

```
/** @var $CLASS$ | \PHPUnit_Framework_MockObject_MockObject $$$MOCKOBJECT$ */
$$$MOCKOBJECT$ = $this->getMockBuilder($CLASS$::class)
    ->disableOriginalConstructor()
    ->setMethods(
        array(
            $METHODS$,
        )
    )
    ->$CALL$();
```

Variables:

| Name | Expression |
| --- | --- |
| MOCKOBJECT |  |
| CLASS |  |
| METHODS |  |
| CALL | enum("getMock", "getMockForAbstractClass") |

```
$$$MOCKOBJECT$->expects($this->$MATCHER$($INDEX$))
->method('$MEHOD$')
->with($WITH$)
->will($this->$WILL$($VALUE$));
```

Variables:

| Name | Expression |
| --- | --- |
| MOCKOBJECT |  |
| MATCHER | enum("once", "at") |
| INDEX |  |
| METHOD |  |
| WITH |  |
| WILL | enum("returnValue", "throwException") |
| VALUE |  |

**Comment by dbalabka** [comment] 2016-01-04 13:53
Thanks you @King2500 I'm ready to test your PR if you will give a hint how it can be installed.

@maxfilatov this solution works well for standart PHPUnit mocking fucntionality, but not for Prophecy. I already have tryed. Please take a look on my example:
![image](https://cloud.githubusercontent.com/assets/1269372/8783727/5593d76c-2f26-11e5-8fd8-33be4fb5c8e7.png)
When I'm using type hinting method `willReturn` will be undefined, because `findOneBy` returns some entity object but not `ObjectProphecy`.

**Comment by dbalabka** [comment] 2016-01-04 13:56
@maxfilatov also about teams. It's easier to once install extension than force each team member to use type hints each time when it needed :)

**Comment by King2500** [comment] 2016-01-04 14:36
It gets a lot uglier with `prophecy` because the returned object is not the mocked object, but a "prophet" which allows mocking methods by magic method calls which themselfs return a `MethodProphecy` object (usually you append then `shouldBeCalled` and/or `willReturn` calls):

![image](https://cloud.githubusercontent.com/assets/4896363/12091548/0cf0e936-b2f8-11e5-9453-1e5f90a407f1.png)

With type hinting you need a variable for every method which makes it less easy to use:

![image](https://cloud.githubusercontent.com/assets/4896363/12091648/99762ef2-b2f8-11e5-90dd-551a9ac2597d.png)

You even need to suppress the warning about methods which have no return type (void), when assigning to variable...

This is just not practical.

All this is solved by the TypeProvider implementation I already did in #7.

**Comment by King2500** [comment] 2016-01-04 14:47
@torinaki I compiled the plugin JAR for you, to test it out:
https://github.com/King2500/phpuaca/releases/download/1.3.0-unstable-typeprovider/phpuaca-1.3.0-unstable-typeprovider.jar

Install it via:
PhpStorm -> Preferences... -> Plugins -> Install plugin from disk...
and restart PhpStorm.
Don't forget to update, when the final 1.3 version of this plugin is released ;-)

**Comment by dbalabka** [comment] 2016-01-04 17:40
@King2500 i see following exception:

```
null
java.util.NoSuchElementException
    at gnu.trove.TIterator.moveToNextIndex(TIterator.java:89)
    at gnu.trove.THashIterator.next(THashIterator.java:67)
    at com.phpuaca.completion.MockedClassTypeProvider.getType(MockedClassTypeProvider.java:71)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:43)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:37)
    at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:52)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:37)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getType(PhpReferenceImpl.java:207)
    at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveGlobal(MemberReferenceImpl.java:142)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:144)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:141)
    at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:136)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:122)
    at com.jetbrains.php.lang.annotator.PhpAnnotatorVisitor.checkAccessModifiers(PhpAnnotatorVisitor.java:406)
    at com.jetbrains.php.lang.annotator.PhpAnnotatorVisitor.visitPhpMethodReference(PhpAnnotatorVisitor.java:388)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:29)
    at com.jetbrains.php.lang.annotator.PhpAnnotator.annotate(PhpAnnotator.java:19)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:162)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:354)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:65)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:288)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:308)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:65)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:314)
    at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:750)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:311)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:65)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:314)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:311)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:280)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



java.util.NoSuchElementException
    at gnu.trove.TIterator.moveToNextIndex(TIterator.java:89)
    at gnu.trove.THashIterator.next(THashIterator.java:67)
    at com.phpuaca.completion.MockedClassTypeProvider.getType(MockedClassTypeProvider.java:71)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:43)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:37)
    at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:52)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:37)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getType(PhpReferenceImpl.java:207)
    at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveGlobal(MemberReferenceImpl.java:142)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:144)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:141)
    at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:136)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:122)
    at com.jetbrains.php.lang.inspections.PhpPassByRefInspection$1.visitPhpMethodReference(PhpPassByRefInspection.java:37)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:29)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:122)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by King2500** [comment] 2016-01-04 18:22
Can you give example PHP code to reproduce this? Thx

**Comment by dbalabka** [comment] 2016-01-04 18:30
@King2500 seems it's appears when vendors aren't installed.

**Comment by King2500** [comment] 2016-01-04 19:31
@torinaki I fixed it and updated the JAR file. Can you test again?

**Comment by dbalabka** [comment] 2016-01-05 11:52
@King2500 exception was gone. Works fine :)

I also have tried to test autocomplition with PhpSpec that uses Prophecy for object mocking, but it doesn't work. Is it possible to make it work in scope of this ticket? It will be very usefull, because I know that [Sylius](https://github.com/Sylius/Sylius) e-commorce use PhpSpec for testing and it has large community.

**Comment by dbalabka** [comment] 2016-01-05 12:00
@King2500 I have reviewed PhpSpec implementation seem it can't  be so easely implemented, because on the front it uses complitly different classes.

**Comment by King2500** [comment] 2016-01-05 15:14
I'll take a look at it.

**Comment by King2500** [comment] 2016-01-06 16:18
IMHO: Since PhpSpec is not part of PHPUnit, it should not be in this plugin.

Max refactored the TypeProviders. You can test them out in the recent unstable-3 release:
https://github.com/maxfilatov/phpuaca/releases/download/1.3.0-unstable-3/phpuaca-1.3.0-unstable-3.jar

**Comment by dbalabka** [comment] 2016-01-06 16:20
@King2500 agree. 

I will test it now

**Comment by King2500** [comment] 2016-01-06 16:20
Btw: small typo in issue title: "Autocompletion"

**Comment by dbalabka** [comment] 2016-01-06 16:37
Found one bug. For some reason methods can't be autocomplited in following example:
![image](https://cloud.githubusercontent.com/assets/1269372/12147910/2bb78958-b4a4-11e5-80ca-594289625939.png)
When I change `EntityManagerInterface` to `EntityManager` autocompletion works. Seems it do not work with interfaces.

**Comment by King2500** [comment] 2016-01-06 16:39
Already reported in #8 ;-)

**Comment by dbalabka** [comment] 2016-01-06 16:43
hmm... but it was working on with previous version somehow. I have checked :)
https://github.com/King2500/phpuaca/releases/download/1.3.0-unstable-typeprovider/phpuaca-1.3.0-unstable-typeprovider.jar

**Comment by King2500** [comment] 2016-01-06 17:35
@torinaki As I said: Max reimplemented it. :)

**Comment by maxfilatov** [comment] 2016-01-07 10:35
Hi @torinaki 

Try to use this new build https://github.com/maxfilatov/phpuaca/releases/download/1.3.0-unstable-4/phpuaca-1.3.0-unstable-4.jar

**Comment by dbalabka** [comment] 2016-02-03 23:24
@maxfilatov sorry about delay. It works. Problem gone.

**Comment by dbalabka** [comment] 2016-03-07 17:01
@maxfilatov  seems this feature already have been released. Am I right?
in https://github.com/maxfilatov/phpuaca/releases/tag/1.3.1

**Closed as completed** 2016-03-07 17:21 UTC
